export { variantListCreator } from './word_trainings_middlewares/variant_list_creator';
export { mistakeCreator } from './spelling_trainings_middlewares/mistake_creator';
export { collectingCommonStatistics } from './common_data_training_middlewares/collecting_common_statistics';
export { clearSelectedWordsCurrentWordset } from './common_data_training_middlewares/clear_selected_words_current_wordset';
export { initializationSplittedAnswerWord } from './spelling_trainings_middlewares/initialization_splitted_answer_word';
export { selectingFullKit } from './word_kits_middleware/selecting_full_words_kit';
export { unSelectingFullWordsKit } from './word_kits_middleware/un_selecting_full_words_kit';
export { personalUserData } from './personal_user_data/personal_user_data_middlewares';
export { continueTrainingMiddleware } from './trainings_middlewares/continue_training_middleware';