export const ADD_LETTER = 'ADD LETTER'; //rename!!!
export const ADD_ANSWER_VOCABULARY_TEST = 'ADD ANSWER VOCABULARY TEST';
export const NEXT_VOCABULARY_TEST_TASK = 'NEXT VOCABULARY TEST TASK';
export const COLLECTING_COMMON_STATISTICS = 'COLLECTING COMMON STATISTICS';  
export const ADD_WORD_TO_VOCABULARY = 'ADD WORD TO VOCABULARY';
export const CREATE_EDUCATION_PLANS = 'CREATE EDUCATION PLANS';
export const CREATE_VARIANT_LIST = 'CREATE VARIANT LIST';
export const CREATE_WORD_SET = 'CREATE WORD SET';
export const CHANGE_USER_PERSONAL_DATA = 'CHANGE_USER_PERSONAL_DATA';
export const DELETE_LETTER = 'DELETE LETTER';
export const CLEAR_SELECTED_WORDS = 'CLEAR SELECTED WORDS';
export const CLEAR_SELECTED_WORDS_CURRENT_WORD_SET = 'CLEAR SELECTED WORDS CURRENT WORD SET';
export const DELETE_SELECTED_WORD = 'DELETE SELECTED WORD';
export const FETCH_WORDS_FOR_MIXING = 'FETCH_WORDS_FOR_MIXING';
export const FETCHING_WORD_SETS_NAMES = 'FETCHING_WORD_SETS_NAMES';
export const FETCHING_WORDS = 'FETCHING WORDS';
export const FETCHING_USER_VOCABULARY = 'FETCHING_USER_VOCABULARY';
export const FETCHING_USER_WORD_SETS = 'FETCHING_USER_WORD_SETS'
export const FETCHING_KNOWLEDGE_TEST = 'FETCHING_KNOWLEDGE_TEST';
export const FETCHING_TRAINING_RESULTS = 'FETCHING_TRAINING_RESULTS';
export const FETCHING_PERSONAL_DATA = 'FETCHING_PERSONAL_DATA';
export const FINISH_TRAINING_ID_001 = 'FINISH TRAINING ID 001';
export const FINISH_TRAINING_ID_002 = 'FINISH TRAINING ID 002';
export const LOGINING = 'LOGINING';
export const SAVE_USER_PERSONAL_DATA = 'SAVE_USER_PERSONAL_DATA';
export const CLEAR_USER_PERSONAL_DATA = 'CLEAR_USER_PERSONAL_DATA';
export const HINT = 'HINT';  //!rename!!!
export const FIFTY_FIFTY = 'FIFTY FIFTY'; //!rename!!!
export const CANCEL_EDIT_PERSONAL_DATA = 'CANCEL_EDIT_PERSONAL_DATA';
export const EXIT_FROM_TRAINING = 'EXIT_FROM_TRAINING'; 
export const INITIALIZATION_CURRENT_TRAINING_MODE = 'INITIALIZATION CURRENT TRAINING MODE';
export const CREATE_STATISTICS_OBJECT_TRAINING_ID_001 = 'CREATE_STATISTICS_OBJECT_TRAINING_ID_001';
export const CREATE_STATISTICS_OBJECT_TRAINING_ID_002 = 'CREATE_STATISTICS_OBJECT_TRAINING_ID_002';
export const INITIALIZATION_TRAINING_ID_002 = 'INITIALIZATION_TRAINING_ID_002';
// export const INITIALIZED_USER_DICTIONARY = 'INITIALIZED USER DICTIONARY';
export const NEXT_TASK_COMMON = 'NEXT TASK COMMON';
export const NEXT_TASK_TRAINING_ID_001 = 'NEXT TASK TRAINING ID 001';
export const NEXT_TASK_TRAINING_ID_002 = 'NEXT TASK TRAINING ID 002'; 
export const DELETE_WORD_FROM_VOCABULARY = 'DELETE WORD FROM VOCABULARY';
export const SELECTING_FULL_KIT = 'SELECTING ALL WORDS';
export const UNSELECTING_FULL_KIT = 'UNSELECTING_FULL_KIT';

export const SELECTING_TASK_VARIANT_TRAINING_ID_001 = 'SELECTING TASK VARIANT TRAINING ID 001';
export const SELECTING_TASK_VARIANT_TRAINING_ID_002 = 'SELECTING TASK VARIANT TRAINING ID 002';

export const SELECTING_WORD = 'SELECTING_WORD'; //! чи потрібе
export const SELECTING_WORD_FROM_USER_VOCABULARY = 'SELECTING_WORD_FROM_USER_VOCABULARY';
export const SELECTING_APPLICATION_LANGUAGE = 'SELECTING_APPLICATION_LANGUAGE';
export const UNSELECTING_WORD = 'UNSELECTING_WORD';//!!!
export const UNSELECTING_WORD_FROM_USER_VOCABULARY = 'UNSELECTING_WORD_FROM_USER_VOCABULARY';


export const SELECTING_TRAINING_MODE = 'SELECTING_TRAINING_MODE';
export const SKIP_WORD = 'SKIP WORD'; //SKIP_TASK //! чи потрібен
export const SKIP_TASK_COMMON = 'SKIP TASK COMMON';
export const SKIP_TASK_TRAINING_ID_001 = 'SKIP TASK TRAINING ID 001';
export const SKIP_TASK_TRAINING_ID_002 = 'SKIP TASK TRAINING ID 002';


export const LOGIN = 'LOGIN';
export const SIGN_IN = 'SIGN_IN';
export const LOG_OUT = 'LOG_OUT';